// <auto-generated />
using System;
using MediaLibrary.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaLibrary.Core.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527151426_AddMovieReleaseDate")]
    partial class AddMovieReleaseDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.ApplicationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiApiKey")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("AiBaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("AiModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AiRecommendationLibraryFingerprint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentAiRecommendationsJson")
                        .IsRequired()
                        .HasMaxLength(30000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOpenSubtitlesEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OmdbApiKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenSubtitlesApiKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenSubtitlesDefaultLanguageCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenSubtitlesEndpoint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenSubtitlesPasswordEncrypted")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenSubtitlesTokenEncrypted")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenSubtitlesUsername")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecentAiRecommendationsJson")
                        .IsRequired()
                        .HasMaxLength(12000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TmdbApiKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TmdbBaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("TmdbReadAccessToken")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationSettings", (string)null);
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.ExternalMetadataCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("HitCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHitAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("Provider", "CacheType", "CacheKey")
                        .IsUnique();

                    b.ToTable("ExternalMetadataCache", (string)null);
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AudioBitrateKbps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AudioChannels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioCodec")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AudioSampleRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodecInfo")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashValue")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaProbeAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("MediaProbeError")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("MediaProbeFileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MediaProbeLastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaProbeStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("MediaProbedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OverallBitrateKbps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteUri")
                        .HasMaxLength(1600)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolutionHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResolutionWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScanPathId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VideoBitrateKbps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoCodec")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("FileName");

                    b.HasIndex("MediaType");

                    b.HasIndex("MovieId");

                    b.HasIndex("ScanPathId");

                    b.HasIndex("SourceConnectionId", "FilePath")
                        .IsUnique();

                    b.ToTable("MediaFiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_MediaFiles_MovieId_EpisodeId_NotBoth", "MovieId IS NULL OR EpisodeId IS NULL");
                        });
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiTagsText")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AutoWatchedBaselineAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefaultMediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmotionTagsText")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GenresText")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdentificationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("IdentifiedConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterLocalPath")
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterRemoteUrl")
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SceneTagsText")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("UserRating")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AutoWatchedBaselineAtUtc");

                    b.HasIndex("DefaultMediaFileId")
                        .IsUnique();

                    b.HasIndex("ImdbId");

                    b.HasIndex("ReleaseYear");

                    b.HasIndex("Title");

                    b.HasIndex("TmdbId");

                    b.ToTable("Movies", (string)null);
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.OnlineSubtitleBinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CacheHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheRelativePath")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DownloadCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Fps")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsAiTranslated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHearingImpaired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMachineTranslated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTrustedUploader")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderFileId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSubtitleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("ReleaseName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Votes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CacheHash");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LastUsedAt");

                    b.HasIndex("ProviderSubtitleId");

                    b.HasIndex("EpisodeId", "Provider", "ProviderFileId", "IsDeleted")
                        .IsUnique();

                    b.HasIndex("MediaFileId", "Provider", "ProviderFileId", "IsDeleted")
                        .IsUnique();

                    b.HasIndex("MovieId", "Provider", "ProviderFileId", "IsDeleted")
                        .IsUnique();

                    b.ToTable("OnlineSubtitleBindings", null, t =>
                        {
                            t.HasCheckConstraint("CK_OnlineSubtitleBindings_Target", "((MovieId IS NOT NULL AND EpisodeId IS NULL AND MediaFileId IS NULL) OR (MovieId IS NULL AND EpisodeId IS NOT NULL AND MediaFileId IS NULL) OR (MovieId IS NULL AND EpisodeId IS NULL AND MediaFileId IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.RatingSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ScoreScale")
                        .HasColumnType("REAL");

                    b.Property<double>("ScoreValue")
                        .HasColumnType("REAL");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("VoteCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MovieId", "SourceName")
                        .IsUnique();

                    b.ToTable("RatingSources", (string)null);
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.ScanPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecursive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceConnectionId", "Path")
                        .IsUnique();

                    b.ToTable("ScanPaths", (string)null);
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.ScanTaskLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("IgnoredFileCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewFileCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonSummaryJson")
                        .HasMaxLength(12000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScanPathId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScannedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdatedFileCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ScanPathId");

                    b.HasIndex("SourceConnectionId");

                    b.ToTable("ScanTaskLogs", (string)null);
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.SourceConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScanAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordEncrypted")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProtocolType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SourceConnections", (string)null);
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.SubtitleBinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoLoaded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubtitleMediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubtitleMediaFileId");

                    b.HasIndex("MediaFileId", "SubtitleMediaFileId")
                        .IsUnique();

                    b.ToTable("SubtitleBindings", (string)null);
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.TvEpisode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefaultMediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationWatchedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastPlayPositionSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StillLocalPath")
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StillRemoteUrl")
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbEpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TvSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultMediaFileId")
                        .IsUnique();

                    b.HasIndex("IsWatched");

                    b.HasIndex("LastPlayedAt");

                    b.HasIndex("TmdbEpisodeId");

                    b.HasIndex("TvSeasonId", "EpisodeNumber")
                        .IsUnique();

                    b.ToTable("TvEpisodes", (string)null);
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.TvSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdentificationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("IdentifiedConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterLocalPath")
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterRemoteUrl")
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TmdbEpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TmdbSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TvSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationStatus");

                    b.HasIndex("TmdbSeasonId");

                    b.HasIndex("TvSeriesId", "SeasonNumber")
                        .IsUnique();

                    b.ToTable("TvSeasons", (string)null);
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.TvSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstAirDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirstAirYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenresText")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterLocalPath")
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterRemoteUrl")
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirstAirYear");

                    b.HasIndex("Name");

                    b.HasIndex("TmdbSeriesId")
                        .IsUnique();

                    b.ToTable("TvSeries", (string)null);
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.UserMovieCollectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenresText")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInLibrary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNotInterested")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWantToWatch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("LibraryVisibilityState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("OmdbLastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OmdbScoreScale")
                        .HasColumnType("REAL");

                    b.Property<double?>("OmdbScoreValue")
                        .HasColumnType("REAL");

                    b.Property<string>("OmdbSourceUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OmdbVoteCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterRemoteUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TmdbRating")
                        .HasColumnType("REAL");

                    b.Property<int?>("TmdbVoteCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsNotInterested");

                    b.HasIndex("IsWantToWatch");

                    b.HasIndex("MovieId");

                    b.HasIndex("TmdbId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("UserMovieCollectionItems", (string)null);
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.UserMovieStateChangeHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NewValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OldValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("StateType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserMovieCollectionItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAtUtc");

                    b.HasIndex("StateType", "ChangedAtUtc");

                    b.HasIndex("TmdbId", "StateType", "ChangedAtUtc");

                    b.ToTable("UserMovieStateChangeHistories", (string)null);
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.UserTvSeasonCollectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirstAirYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenresText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNotInterested")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWantToWatch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("LibraryVisibilityState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("OriginalSeriesTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterRemoteUrl")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeasonTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TmdbSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TvSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TvSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("IsNotInterested");

                    b.HasIndex("IsWantToWatch");

                    b.HasIndex("TmdbSeasonId");

                    b.HasIndex("TmdbSeriesId");

                    b.HasIndex("TvSeasonId");

                    b.HasIndex("TvSeriesId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("TmdbSeriesId", "SeasonNumber");

                    b.ToTable("UserTvSeasonCollectionItems", (string)null);
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.UserTvSeasonStateChangeHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NewValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OldValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeasonTitle")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesTitle")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("StateType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TmdbSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TvSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TvSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserTvSeasonCollectionItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAtUtc");

                    b.HasIndex("StateType", "ChangedAtUtc");

                    b.HasIndex("TvSeasonId", "StateType", "ChangedAtUtc");

                    b.HasIndex("TmdbSeriesId", "SeasonNumber", "StateType", "ChangedAtUtc");

                    b.ToTable("UserTvSeasonStateChangeHistories", (string)null);
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.WatchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationWatchedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastPlayPositionSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("MovieId");

                    b.ToTable("WatchHistories", null, t =>
                        {
                            t.HasCheckConstraint("CK_WatchHistories_MovieId_EpisodeId_ExactlyOne", "(MovieId IS NOT NULL AND EpisodeId IS NULL) OR (MovieId IS NULL AND EpisodeId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.WatchInsightCacheEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAutoRefreshAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastManualRefreshAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RefreshedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("IsStale");

                    b.HasIndex("Kind");

                    b.HasIndex("Kind", "ScopeKey")
                        .IsUnique();

                    b.ToTable("WatchInsightCacheEntries", (string)null);
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.MediaFile", b =>
                {
                    b.HasOne("MediaLibrary.Core.Models.Entities.TvEpisode", "Episode")
                        .WithMany("MediaFiles")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MediaLibrary.Core.Models.Entities.Movie", "Movie")
                        .WithMany("MediaFiles")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MediaLibrary.Core.Models.Entities.ScanPath", "ScanPath")
                        .WithMany("MediaFiles")
                        .HasForeignKey("ScanPathId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MediaLibrary.Core.Models.Entities.SourceConnection", "SourceConnection")
                        .WithMany("MediaFiles")
                        .HasForeignKey("SourceConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("Movie");

                    b.Navigation("ScanPath");

                    b.Navigation("SourceConnection");
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.Movie", b =>
                {
                    b.HasOne("MediaLibrary.Core.Models.Entities.MediaFile", "DefaultMediaFile")
                        .WithOne("DefaultForMovie")
                        .HasForeignKey("MediaLibrary.Core.Models.Entities.Movie", "DefaultMediaFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultMediaFile");
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.OnlineSubtitleBinding", b =>
                {
                    b.HasOne("MediaLibrary.Core.Models.Entities.TvEpisode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MediaLibrary.Core.Models.Entities.MediaFile", "MediaFile")
                        .WithMany("OnlineSubtitleBindings")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MediaLibrary.Core.Models.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Episode");

                    b.Navigation("MediaFile");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.RatingSource", b =>
                {
                    b.HasOne("MediaLibrary.Core.Models.Entities.Movie", "Movie")
                        .WithMany("RatingSources")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.ScanPath", b =>
                {
                    b.HasOne("MediaLibrary.Core.Models.Entities.SourceConnection", "SourceConnection")
                        .WithMany("ScanPaths")
                        .HasForeignKey("SourceConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceConnection");
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.ScanTaskLog", b =>
                {
                    b.HasOne("MediaLibrary.Core.Models.Entities.ScanPath", "ScanPath")
                        .WithMany("ScanTaskLogs")
                        .HasForeignKey("ScanPathId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MediaLibrary.Core.Models.Entities.SourceConnection", "SourceConnection")
                        .WithMany("ScanTaskLogs")
                        .HasForeignKey("SourceConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScanPath");

                    b.Navigation("SourceConnection");
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.SubtitleBinding", b =>
                {
                    b.HasOne("MediaLibrary.Core.Models.Entities.MediaFile", "MediaFile")
                        .WithMany("SubtitleBindings")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaLibrary.Core.Models.Entities.MediaFile", "SubtitleMediaFile")
                        .WithMany("SubtitleBindingsAsSubtitle")
                        .HasForeignKey("SubtitleMediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");

                    b.Navigation("SubtitleMediaFile");
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.TvEpisode", b =>
                {
                    b.HasOne("MediaLibrary.Core.Models.Entities.MediaFile", "DefaultMediaFile")
                        .WithOne("DefaultForEpisode")
                        .HasForeignKey("MediaLibrary.Core.Models.Entities.TvEpisode", "DefaultMediaFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MediaLibrary.Core.Models.Entities.TvSeason", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("TvSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultMediaFile");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.TvSeason", b =>
                {
                    b.HasOne("MediaLibrary.Core.Models.Entities.TvSeries", "Series")
                        .WithMany("Seasons")
                        .HasForeignKey("TvSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.UserMovieCollectionItem", b =>
                {
                    b.HasOne("MediaLibrary.Core.Models.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.UserTvSeasonCollectionItem", b =>
                {
                    b.HasOne("MediaLibrary.Core.Models.Entities.TvSeason", null)
                        .WithMany("CollectionItems")
                        .HasForeignKey("TvSeasonId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.WatchHistory", b =>
                {
                    b.HasOne("MediaLibrary.Core.Models.Entities.TvEpisode", "Episode")
                        .WithMany("WatchHistories")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MediaLibrary.Core.Models.Entities.MediaFile", "MediaFile")
                        .WithMany("WatchHistories")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediaLibrary.Core.Models.Entities.Movie", "Movie")
                        .WithMany("WatchHistories")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Episode");

                    b.Navigation("MediaFile");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.MediaFile", b =>
                {
                    b.Navigation("DefaultForEpisode");

                    b.Navigation("DefaultForMovie");

                    b.Navigation("OnlineSubtitleBindings");

                    b.Navigation("SubtitleBindings");

                    b.Navigation("SubtitleBindingsAsSubtitle");

                    b.Navigation("WatchHistories");
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.Movie", b =>
                {
                    b.Navigation("MediaFiles");

                    b.Navigation("RatingSources");

                    b.Navigation("WatchHistories");
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.ScanPath", b =>
                {
                    b.Navigation("MediaFiles");

                    b.Navigation("ScanTaskLogs");
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.SourceConnection", b =>
                {
                    b.Navigation("MediaFiles");

                    b.Navigation("ScanPaths");

                    b.Navigation("ScanTaskLogs");
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.TvEpisode", b =>
                {
                    b.Navigation("MediaFiles");

                    b.Navigation("WatchHistories");
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.TvSeason", b =>
                {
                    b.Navigation("CollectionItems");

                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("MediaLibrary.Core.Models.Entities.TvSeries", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
